import { MigrationInterface, QueryRunner } from "typeorm";

export class Updates1773375145225 implements MigrationInterface {
    name = 'Updates1773375145225'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP CONSTRAINT "PK_a7e0c0895ceb856a1420ce991fc"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "CV" ADD CONSTRAINT "PK_a7e0c0895ceb856a1420ce991fc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "applicantId"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "applicantId" uuid`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "jobId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "jobId" uuid`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "applicantId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "applicantId" uuid`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "REL_f04802c55e270cf2b9f70d6e42"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "cvId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "cvId" uuid`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "UQ_f04802c55e270cf2b9f70d6e42d" UNIQUE ("cvId")`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_ba4845b5f720bc463a8d673a120"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "PK_0d3212120f4ecedf90864d7e298"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "userORcompanyId"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "userORcompanyId" uuid`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_cbfb1d1219454c9b45f1b3c4274"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "job_title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "location" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "linkedIn_profile" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CV" ADD CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2" FOREIGN KEY ("applicantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0" FOREIGN KEY ("applicantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d" FOREIGN KEY ("cvId") REFERENCES "CV"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801" FOREIGN KEY ("companyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_ba4845b5f720bc463a8d673a120" FOREIGN KEY ("userORcompanyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_cbfb1d1219454c9b45f1b3c4274" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_cbfb1d1219454c9b45f1b3c4274"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_ba4845b5f720bc463a8d673a120"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "linkedIn_profile" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "location" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "job_title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_cbfb1d1219454c9b45f1b3c4274" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "userORcompanyId"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "userORcompanyId" integer`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "PK_0d3212120f4ecedf90864d7e298"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_ba4845b5f720bc463a8d673a120" FOREIGN KEY ("userORcompanyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "companyId" integer`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801" FOREIGN KEY ("companyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "UQ_f04802c55e270cf2b9f70d6e42d"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "cvId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "cvId" integer`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "REL_f04802c55e270cf2b9f70d6e42" UNIQUE ("cvId")`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "applicantId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "applicantId" integer`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "jobId"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "jobId" integer`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0" FOREIGN KEY ("applicantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "applicantId"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "applicantId" integer`);
        await queryRunner.query(`ALTER TABLE "CV" DROP CONSTRAINT "PK_a7e0c0895ceb856a1420ce991fc"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CV" ADD CONSTRAINT "PK_a7e0c0895ceb856a1420ce991fc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "CV" ADD CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2" FOREIGN KEY ("applicantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d" FOREIGN KEY ("cvId") REFERENCES "CV"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
    }

}
