import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateAllTables1774622031620 implements MigrationInterface {
    name = 'UpdateAllTables1774622031620'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "respondedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."jobOffer_status_enum" AS ENUM('Pending', 'Accepted', 'Rejected', 'Expired')`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "status" "public"."jobOffer_status_enum" NOT NULL DEFAULT 'Pending'`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD "resultId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD "durationMin" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "deadline" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "startDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" ADD "startDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."feedback_nextstep_enum" RENAME TO "feedback_nextstep_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_nextstep_enum" AS ENUM('Offered', 'rejected', 'Another Interview')`);
        await queryRunner.query(`ALTER TABLE "feedback" ALTER COLUMN "nextStep" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "feedback" ALTER COLUMN "nextStep" TYPE "public"."feedback_nextstep_enum" USING "nextStep"::"text"::"public"."feedback_nextstep_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_nextstep_enum_old"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP COLUMN "scheduledAt"`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reject-cv" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reject-cv" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "hiredAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "hiredAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "screenAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "screenAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "sendOfferAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "sendOfferAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "interviewAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "interviewAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "rejectAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "rejectAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "startDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "endDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "endDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "rejectAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "rejectAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "interviewAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "interviewAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "sendOfferAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "sendOfferAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "screenAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "screenAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "hiredAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "hiredAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "reject-cv" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reject-cv" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP COLUMN "scheduledAt"`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD "scheduledAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_nextstep_enum_old" AS ENUM('Offered', 'rejected', 'Another Interview', 'Hold')`);
        await queryRunner.query(`ALTER TABLE "feedback" ALTER COLUMN "nextStep" TYPE "public"."feedback_nextstep_enum_old" USING "nextStep"::"text"::"public"."feedback_nextstep_enum_old"`);
        await queryRunner.query(`ALTER TABLE "feedback" ALTER COLUMN "nextStep" SET DEFAULT 'Hold'`);
        await queryRunner.query(`DROP TYPE "public"."feedback_nextstep_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."feedback_nextstep_enum_old" RENAME TO "feedback_nextstep_enum"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CV" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "CV" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "deadline"`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP COLUMN "durationMin"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP COLUMN "resultId"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."jobOffer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "respondedAt"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP COLUMN "expiresAt"`);
    }

}
