export enum EVENT_TYPE {
  SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL",
  SEND_RESET_PASSWORD = "SEND_RESET_PASSWORD",
  SEND_RESTORE_EMAIL = "SEND_RESTORE_EMAIL",
}

export enum STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
  PROCESSING ='PROCESSING'
}
